# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc691def0b270972e3f75f710301230035f4f56e56f8768ebb88ac78dcbdc6b59a50bbfdc094198bdd011b867bfeda6723f52a92845d7266e17cbc288c0b1fe

test:
  secret_key_base: e1c88d1a04bdfe72fff2b7e403954e7232740742afd74e9ad2abdbf42ddb327001f94c1b78ceff075af505675ddeaecad429a74638f3dfb98eb71390d53692b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
